### ISSUE TITLE
No  examples using key / pair authentication which is the preferred metho

### ISSUE THREAD

**Issue by MiguelElGallo** [Snowflake-Labs/snowflake-cli-action#16]
Hello,
You can take the example from here:

https://github.com/MiguelElGallo/SnowCLI

**Comment by sfc-gh-jvasquezrojas** [comment]
Add example in readme in this [PR](https://github.com/Snowflake-Labs/snowflake-cli-action/pull/24/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
