### ISSUE TITLE
snow git execute failing in GitHub actions with "No files matched pattern" error

### ISSUE THREAD

**Issue by sg-schaudhuri** [Snowflake-Labs/snowflake-cli-action#20]
I am able to execute the command from VS Code. However, in GitHub actions I get the error "No files matched pattern". How do I troubleshoot this?

test connection, fetch, list repo and branches work fine in GitHub Actions, but not execute.

VS code local - works fine
![local_vs_code_works_fine](https://github.com/user-attachments/assets/c9dc20bd-e1c7-4b9e-8d51-2d0c33d3a49b)

GitHub Action - fails
![github_action_error](https://github.com/user-attachments/assets/7de0714f-b8ec-4eee-bd92-f25a0d3b1c1a)

**Comment by sfc-gh-jvasquezrojas** [comment]
Did you checkout the code? You have to use this action first https://github.com/marketplace/actions/checkout

**Comment by sg-schaudhuri** [comment]
yes, I am doing actions/checkout@v4 prior to Snowflake-Labs/snowflake-cli-action@v1

**Comment by sfc-gh-jvasquezrojas** [comment]
What OS and CLI version are you using in both cases?

**Comment by sg-schaudhuri** [comment]
I am using ubuntu-latest in GitHub Action:
RUNNER_OS=Linux
ImageOS=ubuntu22
ImageVersion=20240721.1.0
Snowflake CLI version: 2.6.1

**Comment by sfc-gh-jvasquezrojas** [comment]
Can you try running `snow git fetch configuration.elt.bi_snowflake` before `snow git execute` command?

**Comment by sfc-gh-jvasquezrojas** [comment]
The `.yml` file is in UTF-8?

**Comment by sg-schaudhuri** [comment]
![git_action_error_screenshot3](https://github.com/user-attachments/assets/488f864b-9e49-44dd-8f3d-10b552f91adc)
![git_action_error_screenshot2](https://github.com/user-attachments/assets/b8fbbccd-cbed-4fec-8dba-75069ce45bad)
![git_action_error_screenshot1](https://github.com/user-attachments/assets/cd7f8950-2bd9-41b7-8fab-603a8627b524)

The encoding of the file is ascii

**Comment by sfc-gh-jvasquezrojas** [comment]
What version of Snowflake CLI are you using in vs code local?

**Comment by sg-schaudhuri** [comment]
Same, Snowflake CLI version: 2.6.1

**Comment by sfc-gh-jvasquezrojas** [comment]
This issue was fixed in Snowflake CLI v2.8.1
