### ISSUE TITLE
Using wrong package name as of snowflake-cli v3.01 

### ISSUE THREAD

**Issue by lizzykerrigan** [Snowflake-Labs/snowflake-cli-action#26]
Hey,

I noticed earlier that one of our Actions failed on the `snowflake-cli-action` step with the following error:

```
No apps associated with package snowflake-cli-labs. Try again with
'--include-deps' to include apps of dependent packages, which are listed
above. If you are attempting to install a library, pipx should not be used.
Consider using pip or a similar tool instead.
```

I've spotted that [v3.01 of `snowflake-cli` has been released](https://github.com/snowflakedb/snowflake-cli/releases/tag/v3.0.1), which includes a breaking change to the package name. Does this action need to be updated to install the new package name?

**Comment by sg-schaudhuri** [comment]
We are also getting this error. Its a breaking change so please provide some workaround till its fix?
![snow_cli_git_error](https://github.com/user-attachments/assets/afe3138a-a403-4516-a809-5c8b11b3f38e)
